---
author: "Carson Sievert"
layout: page
permalink: /cv/
urlcolor: cyan
output: 
  pdf_document: 
    latex_engine: "lualatex" 
    includes:
      in_header: cv-in-header.tex
      before_body: cv-before-body.tex
  html_document:
    keep_md: true
---

## Education

* Ph.D. in Statistics, Iowa State University \hfill (Spring 2017)
    * __Thesis__: Interfacing R with Web Technologies for Interactive Statistical Graphics and Computing with Data ([preprint](https://github.com/cpsievert/phd-thesis))
* M.S. in Statistics, Iowa State University \hfill (May 2013)
	  * __Thesis:__ Tools for Collecting and Analyzing MLB PITCHf/x Data ([slides](http://cpsievert.github.io/slides/pitchRx/CC/))
* Double B.A. in Mathematics & Economics, Saint John's University \hfill (May 2010)

## Experience
  
__Software Developer__, [plotly](https://plot.ly/). May 2015 - Present

* Maintainer and lead developer of plotly's open-source R package. I also wrote an [online & interactive book](https://cpsievert.github.io/plotly_book/) explaining the project.

__Research Assistant__, [Monash University](http://www.monash.edu/). September 2015 - May 2016

* Advise honours student research and present workshops on data science in R.
    
__Lecturer/TA__, [Iowa State University](http://www.stat.iastate.edu/). Aug. 2011 - May 2015

* Instructor for the online version of 'Intro to Business Statistics' (since Summer 2014).
* Course instructor for [Intro to Business Statistics](http://www.registrar.iastate.edu/catalog/2009-11/courses/stat.html#200). (Since Fall 2012)
* Teaching Assistant for [Statistical Methods for Research Workers](http://www.registrar.iastate.edu/catalog/2009-11/courses/stat.html#400). (Summer 2012)
* Grading supervisor for Intro to Business Statistics. (Fall 2011 & Spring 2012)
    
__Software Developer__, [Google Summer of Code](http://www.google-melange.com/gsoc/homepage/google/gsoc2014). Summer 2014 & 2015

* Served as a student in summer 2014 and a mentor in summer 2015 for  [__animint__](https://github.com/tdhock/animint); an R package for creating web-based interactive graphics and animations using ggplot2's grammar of graphics implementation.
  
__Research Intern__, [Statistics Research Department at AT&T Labs](http://stats.research.att.com/). Summer 2013

* Authored the R package [__LDAvis__](https://github.com/cpsievert/LDAvis) with [Kenny Shirley](http://www2.research.att.com/~kshirley/).
	
__Data Analyst__, [Hardwick-Day Inc.](http://hardwickday.com/) Nov. 2010 - Nov. 2011

* Developed an algorithm for the company's web-based [Net Price Calculators](http://hardwickday.com/capabilities/net-price-calculator) (projected to generate over $3M in new revenue over five years).

## Publications

### Book Chapters

* Carson Sievert and Brian Mills (2017). "Using Publicly Available Baseball Data to Measure and Evaluate Pitching Performance" in [Handbook of Statistical Methods and Analyses in Sports](https://www.crcpress.com/Handbook-of-Statistical-Methods-and-Analyses-in-Sports/Albert-Glickman-Swartz-Koning/p/book/9781498737364), edited by Jim Albert, Mark E. Glickman, Tim B. Swartz, and Ruud H. Koning. Chapman & Hall/CRC. ISBN 9781498737364. ([preprint](pitching-chapter.pdf))

### Journal Articles

* Carson Sievert (2014). [Taming PITCHf/x Data with pitchRx and XML2R](http://journal.r-project.org/archive/2014-1/sievert.pdf). [The R Journal](http://journal.r-project.org/). 6(1).

### Workshop Papers

* Carson Sievert and Kenny Shirley (2014). [LDAvis: A Method for Visualizing and Interpreting Topics](http://nlp.stanford.edu/events/illvi2014/papers/sievert-illvi2014.pdf). [Workshop on Interactive Language Learning, Visualization, and Interfaces at the Association for Computational Linguistics](http://nlp.stanford.edu/events/illvi2014/index.html). Baltimore, Maryland, 2014.

### Manuscripts

* Carson Sievert (2016). [plotly for R](https://cpsievert.github.io/plotly_book/).
* Carson Sievert (2016). [Interactive data visualization on the web using R](https://github.com/cpsievert/phd-thesis/blob/master/plotly.Rmd).
* Carson Sievert, Toby Dylan Hocking, and Susan VanderPlas (2015). [Animint: A Grammar for Interactive Animations](https://github.com/tdhock/animint-paper/blob/master/HOCKING-animint.pdf)

## Talks

All talks given in 2016 (and beyond) are listed here -- <http://cpsievert.github.io/talks/>

### Invited

* Dynamic Interactive Web Graphics for Data Analysis ([slides](http://cpsievert.github.io/slides/web-graphics/murdoch)). Murdoch Childrens Research Institute. Melbourne, Australia. December, 2015
* Interactive and Dynamic Web-Based Statistical Graphics ([slides](http://cpsievert.github.io/slides/web-graphics/wehi/#1)). Walter and Eliza Hall Institute for Medical Research. Melbourne, Australia. September, 2015
* Acquiring, Visualizing, and Modeling MLB Umpire Strike/Ball Decisions with PITCHf/x Data ([slides](http://cpsievert.github.io/slides/pitchRx/jsm15/)). Joint Statistical Meetings. Seattle, WA. August, 2015
* Recent Advances in Interactive Graphics for Data Analysis ([slides](http://cpsievert.github.io/slides/web-graphics/jsm15/)). Joint Statistical Meetings. Seattle, WA. August, 2015
* Web Scraping in R ([slides](http://cpsievert.github.io/slides/web-scraping/20150612/#1)). Great Plain R Users Group, Sioux Falls, SD. June, 2015

### Selected

* [Reproducible web documents with R, knitr & Markdown](http://www.stat.iastate.edu/seminars/seminar.html?id=968), ISU Graphics Working Group ([slides](http://cpsievert.github.io/slides/markdown/)). November, 2013.
* LDAVis: A Method for Visualizing and Interpreting Topics ([slides](http://cpsievert.github.io/slides/LDAvis/)). Joint Statistical Meetings.  Boston, Massachusettes. August, 2014.
* An interactive visualization platform for interpreting topic models ([slides](http://cpsievert.github.io/slides/LDA/0926/) and [video](https://www.dropbox.com/s/datl8sshpp859sh/LDAviz.mov)). ISU Graphics Working Group. August, 2013.
* pitchRx: Tools for Collecting and Analyzing Major League Baseball PITCHf/x Data ([slides](http://cpsievert.github.io/slides/pitchRx/jsm/)). Joint Statistical Meetings.  Montreal, Canada. August, 2013.
* Play for Pay: the Effects of 'Walk Year' Performance on MLB Free Agent Contracts, Scholarship Day. St. Joseph, MN. 04/2010.
* A Mathematical Perspective of Voting, Pi Mu Epsilon's National Conference at MathFest. Portland, OR. 08/2009.
* An Application of Auction Theory to the MLB Free Agent Market, with Zhishan Guo. Mathematical Association of America's MathFest. Madison, WI. 08/2008.

## Honors/Awards

* Invited participant of [2016 rOpenSci Unconference Australia](http://auunconf.ropensci.org/).
* Awarded first place in the [2014 statistical graphics video competition](http://web.archive.org/web/20140215133100/http://streaming.stat.iastate.edu/~dicook/video-competition/) for [this submission](http://web.archive.org/web/20160509234133/http://stat-graphics.org/movies/ldavis.html). 
* Invited participant of the [2014 rOpenSci hackathon](http://ropensci.github.io/hackathon/) (see my [blog post](https://ropensci.org/blog/2014/04/16/topic-modeling-in-R/))
* Invited member of the National Mathematics Honor Society - Pi Mu Epsilon
* Invited member of the Economics Honor Society - Omicron Kappa Sigma
* President's scholar and Dean's List recipient
