---
title: "Untitled"
author: "Carson Sievert"
date: "March 17, 2015"
output: html_document
---

This [**animint**](https://github.com/tdhock/animint) example uses tipping data made available via the [**reshape2**](http://cran.r-project.org/web/packages/reshape2/index.html) package:

```{r echo = FALSE, message = FALSE}
knitr::opts_chunk$set(message = FALSE)
```

```{r}
data(tips, package = "reshape2")
tips$sex_smoker <- with(tips, interaction(sex, smoker))
head(tips)
```


The following code will create a web-based interactive visualization that can be used to explore relationship between `total_bill` and `tip` conditioned on different values of sex and smoker.

```{r}
library(animint)
p1 <- ggplot() +
  geom_point(data = tips, position = "jitter",
    aes(x = sex, y = smoker, colour = sex_smoker, 
        clickSelects = sex_smoker)) + theme(legend.position = "none")
p2 <- ggplot() +
  geom_point(data = tips, 
    aes(x = total_bill, y = tip, colour = sex_smoker,
        showSelected = sex_smoker, tooltip = time))
plots <- list(plot1 = p1, plot2 = p2)
# enable multiple selection
plots$selector.types <- list(sex_smoker = "multiple")
# select all values by default
plots$first <- list(sex_smoker = unique(tips$sex_smoker))
```

```{r eval = FALSE}
animint2dir(plots)
```

```{r echo = FALSE}
structure(plots, class = "animint")
```

