#!/usr/bin/env Rscript

stopifnot(packageVersion('knitr') >= '1.2')
# install dependencies
for (i in setdiff(c(
  'Cairo',
  'animation',
  'knitr',
  'hexbin',
  'RColorBrewer'
), .packages(TRUE))) {
  install.packages(i)
}

# formatR indent 2 spaces; print width 65; no progress
options(reindent.spaces = 2, KNITR_WIDTH = 65)

library(knitr)
stopifnot('_source' %in% list.files()) # run me from the root directory

opts_chunk$set(
  pars = list(mar = c(4, 4, .1, .1), mgp = c(2, 1, 0), bg = 'white'),
  cache = TRUE
)
knit_hooks$set(pars = function(before, options, envir) {
  if (before) do.call(par, options$pars)
}, webgl = hook_webgl, rgl = hook_rgl, crop = hook_pdfcrop)
opts_knit$set(animation.fun = hook_r2swf, stop_on_error = 2L)


invisible(local({
  f = commandArgs(TRUE)
  base = sub('\\.[Rr]md$', '', basename(f))
  message(base)
 
  # each source file corresponds to a separate fig.path and cache.path
  opts_chunk$set(cache.path = paste('cache', base, '', sep = '/'),
                 fig.path = paste('figs', base, '', sep = '/'))
  # opts_knit$set(base.dir = normalizePath('figures', mustWork = TRUE))
  # save images to my Dropbox folder 'http://dl.dropbox.com/u/56809970/blog/'
  # issue with animations under Google Chrome for some reason - SciAnimator
  # keeps on fetching images from Dropbox
  # opts_knit$set(base.url = 'http://dl.dropbox.com/u/56809970/blog/')
  # Y NOT GITHUB? See https://github.com/jfisher-usgs/jfisher-usgs.github.com/blob/master/R/KnitPost.R
  opts_knit$set(base.url='http://raw.github.com/cpsievert/cpsievert.github.com/master/')
  render_jekyll()
  message(f)
  wrap_rmd(f, width = 100)  # reflow long lines in Rmd
  
  knit(f, paste('_posts/', base, '.md', sep = ''), envir = globalenv(), quiet = TRUE)
}))