% Real Time MLB PITCHf/x Animations
% Carson Sievert
% `r library(lubridate); paste(month(Sys.Date()), day(Sys.Date()), year(Sys.Date()), sep = "/")`

```{r setup, include=FALSE, message=FALSE, cache=FALSE}
require(devtools)
install_github('pitchRx', 'cpsievert')
library(pitchRx)
if (!require(knitr)) install_github('knitr', 'yihui')
require(R2SWF) #required for animation to use hook_r2swf function
opts_knit$set(animation.fun = hook_r2swf)
opts_chunk$set(fig.path="figure/", cache.path="cache/", dev='CairoPNG', fig.show='animate', interval=0.01, fig.align='center', fig.width=8, fig.height=7, fig.cap='', warning=FALSE, message=FALSE, echo=FALSE) #NOTE: interval=0.01 makes the animation real-time!
```

```{r getData, include=FALSE, cache=TRUE}
data <- scrapeFX(start="2011-01-01",
  end="2012-01-01", type="pitcher",
  player=c("Mariano Rivera", "Phil Hughes"))
FX <- join(data$pitch, data$atbat, 
  by = c("num", "url"), type = "inner")
pitches <- subset(FX, pitch_type %in% 
  c("FF", "FC"))
```

## Default Plot

```{r animate1}
animateFX(pitches)
```

## Facet by batter stance

```{r animate2}
animateFX(pitches, layer = facet_grid(.~stand))
```

## Facet by batter stance and pitcher's name

```{r animate3}
animateFX(pitches, facet_grid(pitcher_name~stand))
```