---
title: Developing data science tools
date: '2017-06-12'
slug: developing-data-science-tools
---

I take great pride in creating software that [enhances the productivity](https://www.youtube.com/watch?v=zMLVjnRZ3dQ&feature=youtu.be&t=10m41s) of other data scientists. After all, data scientists need to *maximize* time spent formulating, examining, and refinining questions about data; and *minimize* time translating those thoughts into machine code. I've [talked](https://cpsievert.github.io/talks/) at [great](http://cpsievert.github.io/talks/20161212a/) [lengths](http://cpsievert.github.io/talks/20161212b/) about how [my work on plotly](https://cpsievert.github.io/plotcon17/talk) fits into this context, which roughly speaking, enables data scientists to leverage the many benefits on web-based visualization *without any knowledge of web technologies*.

<!-- TODO: web-based tools suck for exploratory visualization? -->


  
This work requires making hard decisions about which abstractions to make, and perhaps more importantly, which abstractions *not* to make. Doing this well requires an intimate knowledge of the most frustating/difficult tasks for most users which means data science tool developers need to: 
  
  1. Be familiar with the vast ecosystem of data science tools or else we risk re-inventing the wheel.[^1]
  1. Get our hands dirty analyzing data, and applying our tools to real problems, or else we risk optimizing for the wrong problem.
  
This is why a good chunk of my time is spent researching the constantly expanding ecosystem of R packages and using some of those tools to do real data analysis.



[^1]: That isn't to say that "re-inventing the wheel" can't be a good thing, especially when it leads to a better wheel. In my opinion, especially in academia, there is too much of a focus on whether tool(s) *exist*, and not nearly enough attention is paid to whether they are *usable*.
  
  <!--
  I feel very fortunate to have spent numerous years of my statistics PhD in this domain learing from mentors that have been this sort of work for 30+ years. They helped me not to forget the importance of 1 and 2
  
  instilled in me how important it is to not become hyper-focused on software engineering problems
  -->
  
  

