---
title: Developing tools for exploratory visualization
date: '2017-06-13'
slug: developing-tools-for-exploratory-visualization
---

I find it incredibly fulfilling to work on projects that [enhance the productivity](https://www.youtube.com/watch?v=zMLVjnRZ3dQ&feature=youtu.be&t=10m41s) of other data scientists. After all, most data scientists need to *maximize* time spent formulating, examining, and refining questions about data; and *minimize* time translating those thoughts into machine code. I've [talked](https://cpsievert.github.io/talks/) at [great](http://cpsievert.github.io/talks/20161212a/) [lengths](http://cpsievert.github.io/talks/20161212b/) about how [my work on plotly](https://cpsievert.github.io/plotcon17/talk) fits into this context, which roughly speaking, allows one to leverage many benefits of interactive web graphics *without any knowledge of web technologies*. 

[If](https://www.nytimes.com/interactive/2014/upshot/mapping-the-spread-of-drought-across-the-us.html) [you](https://www.nytimes.com/interactive/2014/04/24/upshot/facebook-baseball-map.html) [keep](https://www.nytimes.com/interactive/2014/upshot/buy-rent-calculator.html) [up](https://www.nytimes.com/2014/04/23/upshot/the-american-middle-class-is-no-longer-the-worlds-richest.html) [with](https://www.nytimes.com/interactive/2014/07/08/upshot/how-the-year-you-were-born-influences-your-politics.html) [online](https://www.nytimes.com/interactive/2014/06/05/upshot/how-the-recession-reshaped-the-economy-in-255-charts.html) [media](https://www.nytimes.com/interactive/2014/11/04/upshot/senate-maps.html), the benefits of interactive web graphics are pretty clear: they can help grab the audience's attention, enchance knowledge transfer, and allow the audience to further investigate detailed information. And yes, assuming you're a web developer, we already have [awesome](https://d3js.org/) [tools](https://github.com/plotly/plotly.js/) for creating web-based data visualizations; but even if you're a [polyglot data science unicorn](https://www.slideshare.net/ryanorban/bridging-the-gap-between-data-science-engineer-building-highperformance-teams/5?src=clipshare), you still shouldn't be writing JavaScript/JSON to do exploratory analysis (where the most useful view of the data is not yet known). That's because [data exploration requires non-linear iteration between data transformation/modeling/visualization](http://r4ds.had.co.nz/explore-intro.html) (which a web browser was not designed to do). That being said, [interactive graphics are certainly useful for exploration](https://plotcon17.cpsievert.me/talk/#9),[^1] which is partially why we've seen a recent explosion in R/Python/Julia interfaces to JavaScript graphing libraries.

[^1]: Assuming that the time spent iterating from one visualization to the next is relatively small.

I feel very fortunate to have maintained the (completely free and open source) [R interface](https://plotly-book.cpsievert.me/) to [plotly.js](https://github.com/plotly/plotly.js) for over 2 years now. I also feel very fortunate to be in a position where the plotly.js maintainers respond very well to my [bug reports and feature requests](https://github.com/plotly/plotly.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3Acpsievert%20).[^2] Now that I've [graduated](/cv.pdf) and had some time to reflect on the past few years, I've been thinking a bit more generally about data science software development, and how I can keep suistaining this type of work through my [consulting](/consulting) services.

[^2]: Having tracked development on similar R packages, like [ggvis](https://github.com/rstudio/ggvis), I'm convinced that a strong relationship amongst development teams (i.e., R and JavaScript devs) is necessary to maintain such a project.

Generally speaking, designing data science software requires making hard decisions about which abstractions to make, and perhaps more importantly, which abstractions *not* to make (especially with respect to visualization). Doing this well requires an intimate knowledge of the most common/frustating/difficult tasks within the given domain, which means data science software developers should: 
  
  1. Be familiar with the vast ecosystem of existing tools or else we risk re-inventing the wheel.[^3]
  1. Get our hands dirty analyzing data, and applying our tools to real data-driven problems, or else we risk working on insignificant problems.
  
[^3]: That isn't to say that "re-inventing the wheel" can't be a good thing, especially when it leads to a better wheel. In my opinion, especially in academia, there is too much of a focus on whether tool(s) *exist*, and not nearly enough attention is paid to whether they are *usable*.
  
This is why I spend a good chunk of my time researching the constantly expanding ecosystem of R packages and using some of those tools to do real data analysis. Doing so not only forces you to [eat your own dog food](https://en.wikipedia.org/wiki/Eating_your_own_dog_food), but helps you focus on the bigger picture, rather than drowning in a sea of issues that don't effect most users. For example, most of the [new linking framework in plotly](https://plotly-book.cpsievert.me/linking-views-without-shiny.html) was motivated and (indirectly) supported by work on [eechidna](/software/#eechidna)/[pedestrians](/software/#pedestrians)/[bcviz](/software/#bcviz). I hope to continue doing this sort of work with the help of more [clients](/consulting) that have interesting data-driven problems and need better ways to explore/present their data visually.

Another thing I've learned through this work is that even the best programming interfaces do about 80% of what you'd like them to do. That number is even smaller for general-purpose visualization software (e.g., plotly) since their scope is so impossibly large. Fortunately, working with open-source tools means that we are (usually) free to modify the software to fit a particular use case. That sounds great in theory, but in practice, it can be a time-consuming and ultimately futile effort without an intimate understanding of the software. Since I have an intimate understanding of plotly and many other R packages, I also offer my [clients](/consulting) the ability to adapt/modify/fix existing open-source tools for a particular project. 

<!--
As someone with a [formal training in statistics](/cv.pdf) who picked up computing/programming relatively informally, I know all too well how easy it is for [statistical thinking to be swamped by unessential & tedious programming tasks](https://plotcon17.cpsievert.me/talk/#5). 

Moreover, expecting data scientists to be polyglot programmers can be harmful: it steals away cognitive effort that could be better spent learning new mathematics/statistical methods, gaining domain expertise, and also contributes to [this unicorn mentality](http://www.rwjf.org/en/library/infographics/infographic-the-myth-of-the-data-scientist-unicorn.html) that the field suffers from. However, the fact remains, if data scientists want to effectively *do* data analysis and *communicate* their results, they need to juggle a myriad of technologies (R, Python, JavaScript, HTML, SVG, etc).

This is especially true if you need to *do* data analysis, then *present* your results to others in a dynamic/interactive web-based format. That is, shifting from the exploratory phase of an analysis to the communication phase can involve an expensive context shift between tools (e.g. R/Python for exploration, JavaScript/D3 for visualization). Moreover, most web-based tools simply weren't designed for fast iteration time *between* common data visualizations, which is a critical


I run into these scenarios quite frequently with other people's software, but admittedly, probably even more so with my own software. As a result, I've built confidence in my ability to rapidly prototype interactive data visualizations, and customize them to fit a particular use case if an existing solution doesn't already exist.

  I feel very fortunate to have spent numerous years of my statistics PhD in this domain learing from mentors that have been this sort of work for 30+ years. They helped me not to forget the importance of 1 and 2
  
  instilled in me how important it is to not become hyper-focused on software engineering problems
  -->
